name: main

on:
  workflow_dispatch:
    # any manual trigger
  push:
    branches:
      # only for the branches specified below
      - main
      - 'release/**'
      - 'feature/**'
      - 'issue/**'
      - '!user/**'  # explicitly no user/ branches [mostly a note that they exist]
  pull_request:
    # any pull request

defaults:
  run:
    # we want all shell scripts to use the basic sh shell by default
    # we make a copy of it at ~/sh so that we can use WSL's shell on
    #    windows, but the regular sh on linux/macos
    shell: /opt/runner/sh {0}

env:
  OMEGA_DEBUG: all
  DO_SET_X_ACTIVATE: false
  DO_SET_X_BOOTSTRAP: false
  DO_SET_X_RUN: false
  DO_SET_X_UPDATE: false
  PY_COLORS: 1

jobs:
  test:
    name: Test - ${{ matrix.os }} - ${{ matrix.tox-env }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [
          macos-latest-x64,
          ubuntu-latest-x64,
          windows_debian-latest-x64,
          windows_ubuntu-latest-x64,
        ]
        tox-env: [
          py38,
          py39,
          py310,
        ]
        include:
          # create additional matrix entries for ubuntu & tox_env
          - tox-env: lint
            os: ubuntu-latest-x64
            python-version: "3.10"
            os-image: ubuntu-latest
            windows-wsl: not_windows
          - tox-env: coverage
            os: ubuntu-latest-x64
            python-version: "3.10"
            os-image: ubuntu-latest
            windows-wsl: not_windows

          # set vars for tox-env
          - tox-env: py38
            python-version: "3.8"
          - tox-env: py39
            python-version: "3.9"
          - tox-env: py310
            python-version: "3.10"

          # set vars for os & conda-forge
          - os: ubuntu-latest-x64
            os-image: ubuntu-latest
            windows-wsl: not_windows
          - os: windows_debian-latest-x64
            os-image: windows-latest
            windows-wsl: Debian
          - os: windows_ubuntu-latest-x64
            os-image: windows-latest
            windows-wsl: Ubuntu-20.04
          - os: macos-latest-x64
            os-image: macos-latest
            windows-wsl: not_windows

    runs-on: ${{ matrix.os-image }}

    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v1

      - if: matrix.windows-wsl != 'not_windows'
        uses: Vampire/setup-wsl@v1
        name: Setup WSL
        id: setup-wsl
        with:
          distribution: ${{ matrix.windows-wsl }}
          wsl-shell-command: sh --noprofile --norc -euo pipefail '{0}'
          set-as-default: 'false'

      - if: matrix.windows-wsl != 'not_windows'
        name: Windows Build Version
        id: windows-build-version
        shell: cmd
        run: |
          ver

      - if: matrix.windows-wsl != 'not_windows'
        name: Setup shell (WSL)
        id: setup-shell-wsl
        shell: bash {0}  # use the regular sh to make ~/sh
        run: |
          WRAPPER_PATH="${{ steps.setup-wsl.outputs.wsl-shell-distribution-wrapper-path }}"
          SOURCE_PATH="/$(command echo "$WRAPPER_PATH" | cut -c1 | tr '[:upper:]' '[:lower:]')$(command echo "$WRAPPER_PATH" | cut -c3- | sed -e 's/\\/\//g')"
          DEST_PATH=/opt/runner/sh
          echo PATH="$PATH"
          cat "${WRAPPER_PATH}"
          umount /c
          mount -t drvfs C: /c -o metadata
          pwd
          wsl -l -v
          mkdir -p "$(dirname "${DEST_PATH}")"
          touch "${DEST_PATH}"
          chown runneradmin "${DEST_PATH}"
          chmod +x "${DEST_PATH}"
          ls -l "${DEST_PATH}"
          "${DEST_PATH}" --version

      - if: matrix.windows-wsl == 'not_windows'
        name: Setup shell (Non-WSL)
        id: setup-shell-non-wsl
        shell: sh {0}  # use the regular sh to make ~/sh
        run: |
          SOURCE_PATH="$(which sh)"
          DEST_PATH=/opt/runner/sh
          echo PATH="$PATH"
          pwd
          sudo mkdir -p "$(dirname "${DEST_PATH}")"
          sudo touch "${DEST_PATH}"
          sudo chown runner "${DEST_PATH}"
          chmod +x "${DEST_PATH}"
          ls -l "${DEST_PATH}"
          "${DEST_PATH}" --version

      - name: Runner Info
        id: runner-info
        shell: sh {0}
        run: |
          echo OS: ${{ runner.os }}
          echo ARCH: ${{ runner.arch }}
          echo matrix:
          echo os: ${{ matrix.os }}
          echo tox-env: ${{ matrix.tox-env }}
          echo windows-wsl: ${{ matrix.windows-wsl }}
          echo Mounts:
          mount -l
          echo Env:
          printenv | sort

      - name: Override Python Version For Work Env
        id: override-python-version
        run: |
          sed -i.old -e 's/  - python=.*/  - python=${{ matrix.python-version }}/' ./conda-environment.yml

      - name: batteries-forking-included
        id: batteries-forking-included
        run: |
          ./bootstrap.sh --dev

      - name: Test - ${{ matrix.tox-env }}
        id: test-tox
        run: |
          . ./activate.sh
          tox -e ${{ matrix.tox-env }} -- -p sugar --force-sugar --color=yes

      - name: Upload BFI Logs
        id: upload-bfi-logs
        if: matrix.tox-env != 'lint'
        uses: actions/upload-artifact@v3
        with:
          name: bfi-logs-${{ matrix.os }}-${{ matrix.tox-env }}
          path: |
            ${{ github.workspace }}/bfi_temp/*/log/*

      - name: Upload Test Report Artifacts
        id: upload-test-report-artifacts
        if: matrix.tox-env != 'lint'
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.os }}-${{ matrix.tox-env }}
          path: |
            .reports/**

      - name: Upload Coverage Artifacts
        id: upload-coverage-artifacts
        if: matrix.tox-env == 'coverage'
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: |
            coverage.xml
            htmlcov/**

  build:
    name: Build Products

    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v1


      - name: Runner Info
        id: runner-info
        run: |
          echo OS: ${{ runner.os }}
          echo ARCH: ${{ runner.arch }}

      - name: batteries-forking-included
        id: batteries-forking-included
        run: |
          ./bootstrap.sh

      - name: Build Package
        id: build-package
        run: |
          . ./activate.sh
          poetry build

      - name: Upload Build Products
        id: upload-build-products
        uses: actions/upload-artifact@v3
        with:
          name: build-products
          path: dist/*

  github-release:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/release')
    name: Create Github Release

    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v1

      - name: Runner Info
        id: runner-info
        run: |
          echo OS: ${{ runner.os }}
          echo ARCH: ${{ runner.arch }}

      - name: batteries-forking-included
        id: batteries-forking-included
        run: |
          ./bootstrap.sh

      - name: Process Version Number
        id: process-version
        run: |
          . ./activate.sh
          echo ::set-output name=version::$(poetry version --short)
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
            || echo ::set-output name=prerelease::true

      - name: Check Tag Doesn't Exist
        id: check-tag-does-not-exist
        run: |
          . ./activate.sh
          echo "${{ steps.process-version.outputs.version }}"
          echo ""
          git tag
          echo ""
          echo "Match:"
          echo "$(git tag | grep -e "^${{ steps.process-version.outputs.version }}$")"
          echo ""
          if [[ $(git tag | grep -e "^${{ steps.process-version.outputs.version }}$") ]]; then
            echo "Tag already exists."
            exit 2
          fi

      - name: Check Branch Name
        id: check-branch-name
        run: |
          . ./activate.sh
          if [[ \
            "$(echo ${{ github.ref_name  }} | sed 's/release\///g;s/\//./g')" != \
            "${{ steps.process-version.outputs.version }}" \
          ]]; then
            echo "Release branch name and version number mismatch."
            exit 2
          fi

      - name: Download Build Products
        id: download-build-products
        uses: actions/download-artifact@v3
        with:
          name: build-products
          path: dist

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          artifacts: "dist/*"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          tag: ${{ steps.process-version.outputs.version }}
          prerelease: ${{ steps.process-version.outputs.prerelease == 'true' }}


  publish:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/release')
    name: Publish to PyPI

    runs-on: ubuntu-latest
    needs: [test, build, github-release]

    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v1

      - name: Runner Info
        id: runner-info
        run: |
          echo OS: ${{ runner.os }}
          echo ARCH: ${{ runner.arch }}

      - name: batteries-forking-included
        id: batteries-forking-included
        run: |
          ./bootstrap.sh

      - name: Download Build Products
        id: download-build-products
        uses: actions/download-artifact@v3
        with:
          name: build-products
          path: dist

      - name: Publish to PyPI
        id: publish-to-pypi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          . ./activate.sh
          poetry publish
